=== monxalo/android-model-agent/data/model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->

<!-- definition of attributes -->
<xs:attribute name="namespace" type="xs:string"/>
<xs:attribute name="prefix" type="xs:string"/>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="type">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="int"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="date"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="isNull" type="xs:boolean"/>
<xs:attribute name="generateIds" type="xs:boolean"/>
<xs:attribute name="ref" type="xs:string"/>
<xs:attribute name="hasAndBelongsToMany" type="xs:string"/>
<xs:attribute name="singular" type="xs:string"/>

<!-- definition of complex elements -->

<xs:element name="field">
  <xs:complexType>
	<xs:attribute ref="name" use="required"/>
	<xs:attribute ref="type" use="required"/>
	<xs:attribute ref="isNull" use="required"/>
	<xs:attribute ref="ref"/>
  </xs:complexType>
</xs:element>

<xs:element name="entity">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="field"/>
    </xs:sequence>
	<xs:attribute ref="name" use="required"/>
	<xs:attribute ref="singular" />
	<xs:attribute ref="generateIds" use="required"/>
	<xs:attribute ref="hasAndBelongsToMany"/>
  </xs:complexType>
</xs:element>

<xs:element name="root">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="entity"/>
    </xs:sequence>
    <xs:attribute ref="namespace" use="required"/>
	<xs:attribute ref="prefix" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema>

=== monxalo/android-model-agent/data/model.xml
<?xml version="1.0" encoding="utf-8"?>
<root namespace="com.example.noteapp" prefix="NotesApp" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="model.xsd">

	<entity name="categories" generateIds="true" singular="category" hasAndBelongsToMany="notePads">
	    <field name="title" isNull="false" type="string" />
	    <field name="date_created" isNull="false" type="date" />
	</entity>
	<entity name="notePads" generateIds="true" hasAndBelongsToMany="categories">
	    <field name="title" isNull="false" type="string" />
	    <field name="date_created" isNull="false" type="date" />
	</entity>
	<entity name="notes" generateIds="true">
	    <field name="title" isNull="false" type="string" />
	    <field name="text" isNull="false" type="string" />
	    <field name="date_created" isNull="false" type="date" />
	    <field name="notepad_id" isNull="false" type="int" ref="notePads._ID"/>
	</entity>
</root>
